server:
  port: 9090

spring:
  application:
    name: API_GATEWAY_1
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:Keys/publicKey.pem
  cloud:
    gateway:
      routes:
        - id: chercheur
          uri: http://localhost:8080
          predicates:
            - Path=/v1/Chercheurs/**
        - id: enseignant
          uri: http://localhost:8085
          predicates:
            - Path=/v1/Enseignants/**
        - id: ProjetDeRecherche
          uri: http://localhost:8083
          predicates:
            - Path=/v1/projets/**

